### ISSUE TITLE
IDEA 2021.2版本 打开时出现这种提示

### ISSUE THREAD

**Issue by zhushizhou** [qeesung/HighlightBracketPair#26]
IDEA 2021.2
Plugin 'io.github.qeesung.component.HighlightBracketPair' failed to initialize and will be disabled. Please restart IntelliJ IDEA.
![image](https://user-images.githubusercontent.com/53800963/127281934-96eced24-c103-4d62-b1e0-a545780fa882.png)

**Comment by maodouzi123** [comment]
不兼容新版本了。。

**Comment by zhushizhou** [comment]
> 不兼容新版本了。。

好像是吧 所以只能先回退版本；如果想用新版本的话，只能卸载这个插件同步设置，再用新版本就可以了（如果没有其他插件问题的话）

**Comment by Klaus-Kin** [comment]
哭了

**Comment by AprilViolet** [comment]
我对HighlightBracketPair这个插件进行了一些兼容的，目前来说在Idea2021.2上没有报错，先用着把。
后面我会重新整理一下代码，进行一些兼容开发。当然如果原作者能够回来继续进行开发是最好的了。
附上新的包，目前只是把报错解决了，源码待我整理之后会放在Github上，后续如果可能我会接收开发
[HighlightBracketPair.zip](https://github.com/qeesung/HighlightBracketPair/files/6901664/HighlightBracketPair.zip)

**Comment by Klaus-Kin** [comment]
@AprilViolet 大佬牛逼

**Comment by luiscarielo83** [comment]
Thanks a lot @AprilViolet

**Comment by zhushizhou** [comment]
@AprilViolet 强啊老哥

**Comment by suibianshuyigebaa** [comment]
> 我对HighlightBracketPair这个插件进行了一些兼容的，目前来说在Idea2021.2上没有报错，先用着把。
> 后面我会重新整理一下代码，进行一些兼容开发。当然如果原作者能够回来继续进行开发是最好的了。
> 附上新的包，目前只是把报错解决了，源码待我整理之后会放在Github上，后续如果可能我会接收开发
> [HighlightBracketPair.zip](https://github.com/qeesung/HighlightBracketPair/files/6901664/HighlightBracketPair.zip)

老哥流弊，太强了

**Comment by cuichaoyu** [comment]
> 我对HighlightBracketPair这个插件进行了一些兼容的，目前来说在Idea2021.2上没有报错，先用着把。
> 后面我会重新整理一下代码，进行一些兼容开发。当然如果原作者能够回来继续进行开发是最好的了。
> 附上新的包，目前只是把报错解决了，源码待我整理之后会放在Github上，后续如果可能我会接收开发
> [HighlightBracketPair.zip](https://github.com/qeesung/HighlightBracketPair/files/6901664/HighlightBracketPair.zip)

  老哥强,如果有更新了,希望老哥回我一下,谢谢了

**Comment by AprilViolet** [comment]
**插件已经更新到idea的Marketplace,可以去[下载](https://plugins.jetbrains.com/plugin/17320-highlightbracketpair)。后面的话会照常的进行更新适配和可能的话增加一些新的功能。**

**Comment by maodouzi123** [comment]
> **插件已经更新到idea的Marketplace,可以去[下载](https://plugins.jetbrains.com/plugin/17320-highlightbracketpair)。后面的话会照常的进行更新适配和可能的话增加一些新的功能。**

请问下，您这个插件目前只支持java吗？

**Comment by qeesung** [comment]
抱歉，最近项目比较忙，我抽空有时间修复一下。

不过也欢迎各位的PR

**Comment by cuichaoyu** [comment]
> 抱歉，最近项目比较忙，我抽空有时间修复一下。
> 
> 不过也欢迎各位的PR

大佬,快更新吧,消失很久了

**Comment by hchoroomi** [comment]
> 抱歉，最近项目比较忙，我抽空有时间修复一下。
> 
> 不过也欢迎各位的PR

Google Translate isn't great translate Chinese language. It sounds like you're back fixing the issue?

In any case, it's good to see you're well! 🙂

**Comment by xsun12131** [comment]
我根据源码下载下来后修改了一些参数，然后就能在我的idea上运行了。idea版本2021.2
[HighlightBracketPair-1.1.2.zip](https://github.com/qeesung/HighlightBracketPair/files/7020271/HighlightBracketPair-1.1.2.zip)
目测的错误原因是api更新。

**Comment by cuichaoyu** [comment]
在vue文件中没生效，JS文件可以，webstorm2021.2.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qeesung/HighlightBracketPair"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月20日(星期五) 下午4:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qeesung/HighlightBracketPair] IDEA 2021.2版本 打开时出现这种提示 (#26)





 
我根据源码下载下来后修改了一些参数，然后就能在我的idea上运行了。idea版本2021.2
 HighlightBracketPair-1.1.2.zip
 目测的错误原因是api更新。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xsun12131** [comment]
> 在vue文件中没生效，JS文件可以，webstorm2021.2.1
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "qeesung/HighlightBracketPair" ***@***.***&gt;; 发送时间:&nbsp;2021年8月20日(星期五) 下午4:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [qeesung/HighlightBracketPair] IDEA 2021.2版本 打开时出现这种提示 (#26) 我根据源码下载下来后修改了一些参数，然后就能在我的idea上运行了。idea版本2021.2 HighlightBracketPair-1.1.2.zip 目测的错误原因是api更新。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
使用这个版本试试
[HighlightBracketPair-1.1.3.zip](https://github.com/qeesung/HighlightBracketPair/files/7144181/HighlightBracketPair-1.1.3.zip)
我测试的可以使用
![image](https://user-images.githubusercontent.com/43137453/132863123-055795d4-8ebe-4a07-a626-9876179b6818.png)

**Comment by cuichaoyu** [comment]
你好，经测试发现大括号，小括号，中括号正常，字符串及箭头符号不能正常高亮，你那边正常吗？

**Comment by xsun12131** [comment]
> 你好，经测试发现大括号，小括号，中括号正常，字符串及箭头符号不能正常高亮，你那边正常吗？

新的修复，试下吧
[HighlightBracketPair-1.1.3.zip](https://github.com/qeesung/HighlightBracketPair/files/7147609/HighlightBracketPair-1.1.3.zip)

**Comment by cuichaoyu** [comment]
你好，是这个效果吗？字符串和箭头符号的效果一样，下面的是箭头符号的
下面这个是字符串的

**Comment by xsun12131** [comment]
> 你好，是这个效果吗？字符串和箭头符号的效果一样，下面的是箭头符号的 下面这个是字符串的

没有图片显示你的问题。按照我的想法，xml下这两个的效果是一样的，因为想着属性的值较短。现在想想是需要不一样。另外，之前发布的版本存在些问题，没有使用vuejs插件的idea会出现没有编辑器的情况，所以我删除了之前的评论。如果想继续使用的话，可以我fork的项目下提出问题，我尽量修改回复。

**Comment by cuichaoyu** [comment]
你好，你fork的项目没有打开issue

**Comment by cuichaoyu** [comment]
这位老哥的包可以正常工作，webstorm2021.2.1,用起来非常不错，强烈推荐[https://github.com/xsun12131/HighlightBracketPair/releases](url)
