### ISSUE TITLE
thanks for the plugin (+less intrusive Dracula scheme)

### ISSUE THREAD

**Issue by AndreiD** [qeesung/HighlightBracketPair#6]
Thanks for the plugin, my eyes thank you for it.

-------- I modified a little the default colors for Dracula, to make them less intrusive
If anyone wants my scheme here it is

[lessintrusivedracula.zip](https://github.com/qeesung/HighlightBracketPair/files/1845750/lessintrusivedracula.zip)

**Comment by qeesung** [comment]
@AndreiD Thanks for your feedback and the brilliant scheme. Hope you love it.
